---
# Install pre-requistes do we can run "oc cluster up"
#
# Based on
#  https://github.com/openshift-evangelists/oc-cluster-wrapper
#   https://developers.redhat.com/blog/2017/02/23/openshift-for-developers-set-up-a-full-cluster-in-under-30-minutes/
#
- hosts: all
  remote_user: root
  vars:
    yum_extra_repo:
      RedHat: rhel-7-server-extras-rpms
      CentOS: centos-openshift-origin
    openshift_version: 3.9
  tasks:

  tasks:
  - name: Get active firewall zones on host
    shell: firewall-cmd --get-zones | grep dockerc
    register: activeZones
    failed_when: no

  - name: Stop playbook if firewall execution not completed
    fail: msg="Firewall commands must be run before executing this playbook activeZones"
    when: activeZones.rc != 0

  #- name: Enable the extras repositories when on RHEL 7 to get Docker
    #command: subscription-manager repos \
             #--enable=rhel-7-server-extras-rpms \
    #when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

  - name: Enable the Centos 7 OpenShift Origin Repo
    yum_repository:
      name: centos-openshift-origin
      description: CentOS OpenShift Origin
      file: centos_paas_repos
      baseurl: 'http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/'
      gpgcheck: no
      enabled: 1
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS'
    when: (ansible_distribution == "Centos" and ansible_distribution_major_version == "7")

  - name: Additional packages needed as our Server for Centos
    yum: 
      name={{item}}
      state=present
    with_items :
     - git
     - wget
     - net-tools
     - bind-utils
     - iptables-services
     - bridge-utils
     - docker
     - origin-clients-{{openshift_version}}.0
    when: (ansible_distribution == "Centos" and ansible_distribution_major_version == "7")

  - name: Additional packages needed as our Server for RHEL
    yum: 
      name={{item}}
      state=present
      enablerepo=rhel-7-server-extras-rpms,rhel-7-server-ose-{{openshift_version}}-rpms,rhel-7-fast-datapath-rpms,rhel-7-server-rpms
    with_items :
     - git
     - wget
     - net-tools
     - bind-utils
     - iptables-services
     - bridge-utils
     - docker
     - atomic-openshift-clients
    when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

  - name: Git clone the oc-cluster-wrapper
    git:
      repo: 'https://github.com/openshift-evangelists/oc-cluster-wrapper'
      dest: /root/oc-cluster-wrapper

#  - name: Create dockerc firewall zone
#    firewalld:
#      zone: dockerc
#      state: enabled
#      permanent: true
  #- name: Create dockerc firewall zone
    #command: firewall-cmd --permanent --new-zone dockerc

  - name: Enable firewall docker zone
    firewalld:
      source: 172.17.0.0/16
      zone: dockerc
      permanent: true
      state: enabled
    notify: restart firewalld


  - name: Enable firewall access for docker services
    firewalld: port={{item}} immediate=true permanent=true state=enabled zone=dockerc
    with_items :
     - 8443/tcp
     - 53/udp
     - 8053/udp
     - 5000/tcp
    notify: restart firewalld

  - name: Enable external service access on 8443 plus port 80 for live services
    firewalld: port={{item}} immediate=true permanent=true state=enabled 
    with_items :
     - 8443/tcp
     - 80/tcp
    notify: restart firewalld

  - name: Make sure we have enabled the insecure docker registry
    lineinfile: dest=/etc/sysconfig/docker
                state=present
                line="INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'"
    notify: update docker

  - name: docker to be running
    systemd:
      name: docker
      state: started
      enabled: yes
      masked: no


  handlers:
    - name: update docker
      systemd:
        name=docker
        state=reloaded
        masked=no

    - name: restart firewalld
      systemd:
        name=firewalld
        state=restarted
        masked=no
