---
# Install pre-requistes do we can run "oc cluster up"
#
# Based on
#  https://github.com/openshift-evangelists/oc-cluster-wrapper
#   https://developers.redhat.com/blog/2017/02/23/openshift-for-developers-set-up-a-full-cluster-in-under-30-minutes/ 
#
- hosts: all
  vars:
  remote_user: root
  tasks:

  - name: Enable the extras repositories when on RHEL 7 to get Docker
    command: subscription-manager repos \
             --enable=rhel-7-server-extras-rpms \
    when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

  - name: Enable the Centos 7 OpenShift Origin Repo
    yum_repository:
      name: centos-openshift-origin
      description: CentOS OpenShift Origin
      file: centos_paas_repos
      baseurl: 'http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/'
      gpgcheck: no
      enabled: 1
      gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS'

  - name: Additional packages needed as our Server
    yum: name={{item}} state=present
    with_items :
     - git
     - docker
     - origin-clients-3.7.0

  - name: Git clone the oc-cluster-wrapper
    git:
      repo: 'https://github.com/openshift-evangelists/oc-cluster-wrapper'
      dest: /root/oc-cluster-wrapper

  - name: Make sure we have enabled the insecure docker registry
    lineinfile: dest=/etc/sysconfig/docker
                state=present
                line="INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16;'"
    notify: update docker

  - name: docker to be running
    systemd:
      name: docker
      state: started
      enabled: yes
      masked: no


  handlers:
    - name: update docker
      systemd:
        name=docker
        state=reloaded
        masked=no
